services:
    grifis_doctrine_table_prefix.subscriber:
        class: Grifis\DoctrineTablePrefixBundle\Subscriber\TablePrefixSubscriber
        arguments: [%grifis_doctrine_table_prefix.prefix%]
        tags:
            - { name: doctrine.event_subscriber }